
[GUI]
	#The position X of Player Temperature UI
	#Range: > -2147483648
	PlayerTemperatureX = 10
	#The position Y of Player Temperature UI
	#Range: > -2147483648
	PlayerTemperatureY = 40
	#Info used for development.
	DebugInfo = false

[Renderer]
	#Force to update chunk rendering.
	ForceChunkRenderUpdate = true
	#Force to update chunk rendering.
	useVanillaCheck = false
	#If snow falls during cold weather, it will gradually cover all solid blocks and grass.
	SnowyWinter = true
	#Occasionally a thicker layer of snow will cover the flowers and grass, especially.
	DeeperSnow = false
	#Blocks below fences and bamboo will also accumulate snow.
	UnderSnow = false
	#Particle.
	Particle = true

[Sound]
	#Ambient Sound.
	Sound = true

